name: build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Installing Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: npm install -g @angular/cli
      - run: npm install
      - run: ng build --project=poc-storybook-library
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v3
        with:
          semantic_version: 19.0.3
        env:
          GITHUB_TOKEN: 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
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
